[hooks]
dynamic_quotes = 10
collections-import-rewrite = 20
reformat-generics = 40
noqa-reformat = 60
ellipsis-reformat = 70
squish_stubs = 80

[config]
indent = "\t"
line_length = 115

[hooks.yapf]
priority = 30

[hooks.isort]
priority = 50

[hooks.yapf.kwargs]
yapf_style = ".style.yapf"

[hooks.isort.kwargs]
indent = "\t\t"
multi_line_output = 8
import_heading_stdlib = "stdlib"
import_heading_thirdparty = "3rd party"
import_heading_firstparty = "this package"
import_heading_localfolder = "this package"
balanced_wrapping = false
lines_between_types = 0
use_parentheses = true
remove_redundant_aliases = true
default_section = "THIRDPARTY"
known_third_party = [
    "dom_toml",
    "domdf_python_tools",
    "flask",
    "github3_py",
    "gunicorn",
    "jinja2",
    "packaging",
    "platformdirs",
    "pybadges",
    "pypi_json",
    "requests",
    "setup_py_upgrade",
    "shippinglabel",
    "typing_extensions",
    "wtforms",
]
known_first_party = "dependency_dash"
